version: '3.8'

services:
  
  postgres_db:
    image: postgres:15
    container_name: apollo_postgres
    environment:
      POSTGRES_USER: apollo_admin
      POSTGRES_PASSWORD: apollo_iot_pass
      POSTGRES_DB: apollo_task
    ports:
      - "5432:5432"
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  
  modbus_server:
    build: .
    container_name: modbus_server
    command: python modbus_server.py
    ports:
      - "5020:5020"

  iot_subscriber:
    build: .
    container_name: iot_subscriber
    command: python mqtt_subscriber.py
    depends_on:
      - postgres_db

  
  iot_publisher:
    build: .
    container_name: iot_publisher
    command: python mqtt_publisher.py
    depends_on:
      - modbus_server